# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CauChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CauChat.Key')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CauChat.Chat')),
            ],
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='bestKey',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='chat',
        ),
        migrations.AddField(
            model_name='reply',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='request',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
